import type { WeatherCodes, WeatherTimeSeries } from "@common/types";

export const mockWeatherResponse: WeatherTimeSeries[] = [
    {
        location: "FAKETOWN",
        time: "2022-08-03T00:00Z",
        midday10MWindSpeed: 6.07,
        midnight10MWindSpeed: 2.8,
        midday10MWindDirection: 236,
        midnight10MWindDirection: 271,
        midday10MWindGust: 9.77,
        midnight10MWindGust: 8.08,
        middayVisibility: 22594,
        midnightVisibility: 25202,
        middayRelativeHumidity: 72.83,
        midnightRelativeHumidity: 80.61,
        middayMslp: 101280,
        midnightMslp: 101380,
        maxUvIndex: 1,
        daySignificantWeatherCode: 7,
        nightSignificantWeatherCode: 0,
        dayMaxScreenTemperature: 22.9,
        nightMinScreenTemperature: 13.24,
        dayUpperBoundMaxTemp: 23.94,
        nightUpperBoundMinTemp: 14.01,
        dayLowerBoundMaxTemp: 21,
        nightLowerBoundMinTemp: 11,
        dayMaxFeelsLikeTemp: 20.47,
        nightMinFeelsLikeTemp: 12.65,
        dayUpperBoundMaxFeelsLikeTemp: 20.94,
        nightUpperBoundMinFeelsLikeTemp: 13.04,
        dayLowerBoundMaxFeelsLikeTemp: 18.19,
        nightLowerBoundMinFeelsLikeTemp: 10.14,
        dayProbabilityOfPrecipitation: 3,
        nightProbabilityOfPrecipitation: 0,
        dayProbabilityOfSnow: 0,
        nightProbabilityOfSnow: 0,
        dayProbabilityOfHeavySnow: 0,
        nightProbabilityOfHeavySnow: 0,
        dayProbabilityOfRain: 3,
        nightProbabilityOfRain: 0,
        dayProbabilityOfHeavyRain: 0,
        nightProbabilityOfHeavyRain: 0,
        dayProbabilityOfHail: 0,
        nightProbabilityOfHail: 0,
        dayProbabilityOfSferics: 0,
        nightProbabilityOfSferics: 0,
        WeatherType: "",
        Description: "",
        MaxTemp: "",
        LowTemp: "",
        MaxFeels: "",
        Wind: 2,
    },
];

export const weatherCodes: WeatherCodes = {
    0: ["sun", "Clear night"],
    1: ["sun", "Sunny day"],
    2: ["cloud", "Partly cloudy (night)"],
    3: ["cloud", "Partly cloudy (day)"],
    5: ["foggy", "Mist"],
    6: ["foggy", "Fog"],
    7: ["cloud", "Cloudy"],
    8: ["cloud", "Overcast"],
    9: ["rain", "Light rain shower (night)"],
    10: ["rain", "Light rain shower (day)"],
    11: ["rain", "Drizzle"],
    12: ["rain", "Light rain"],
    13: ["rain", "Heavy rain shower (night)"],
    14: ["rain", "Heavy rain shower (day)"],
    15: ["rain", "Heavy rain"],
    16: ["snow", "Sleet shower (night)"],
    17: ["snow", "Sleet shower (day)"],
    18: ["snow", "Sleet"],
    19: ["snow", "Hail shower (night)"],
    20: ["snow", "Hail shower (day)"],
    21: ["snow", "Hail"],
    22: ["snow", "Light snow shower (night)"],
    23: ["snow", "Light snow shower (day)"],
    24: ["snow", "Light snow"],
    25: ["snow", "Heavy snow shower (night)"],
    26: ["snow", "Heavy snow shower (day)"],
    27: ["snow", "Heavy snow"],
    28: ["thunder", "Thunder shower (night)"],
    29: ["thunder", "Thunder shower (day)"],
    30: ["thunder", "Thunder"],
};
